### ISSUE TITLE
Cleanup duplicate SSH keys

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooni-sysadmin#140]
GH template had an issue that SSH host keys were same for all VMs.
We still have some VMs having same RSA-2048 and Ed25519 keys:
`ssh-keyscan -t rsa,ed25519 $hosts | sort -k 3`
- [x] b.collector.ooni.io
- [x] b.web-connectivity.th.ooni.io
- [x] demo.probe.ooni.io
- [x] measurements.ooni.io
- [x] munin.ooni.io
- [x] ooni-measurements-db.infra.ooni.io
- [x] staging.measurements.ooni.io

IMHO these keys should be re-generated.

**Comment by bassosimone** [comment]
> IMHO these keys should be re-generated.
👍
