### ISSUE TITLE
Cleanup GH hosts that are not in inventory

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooni-sysadmin#175]
Following hosts are in `gh-droplets.json` and are NOT in `inventory` right now.

- [x] `{"v4":"199.119.112.12","name":"test-qemu.infra.ooni.io","dc":"Washington DC"}`
- [x] `{"v4":"37.218.240.117","name":"design.ooni.io","dc":"Hong Kong"}`
- [x] `{"v4":"37.218.240.156","name":"ooniprobe-deb-testing","dc":"Hong Kong"}`
- [x] `{"v4":"37.218.240.158","name":"afwrk01","dc":"Hong Kong"}`
- [x] `{"v4":"37.218.240.159","name":"afwrk02","dc":"Hong Kong"}`
- [x] `{"v4":"37.218.240.160","name":"afwrk03","dc":"Hong Kong"}`
- [x] `{"v4":"37.218.240.162","name":"afwrk04","dc":"Hong Kong"}`
- [ ] `{"v4":"37.218.240.93","name":"wiki.ooni.io","dc":"Hong Kong"}`
- [x] `{"v4":"37.218.242.175","name":"amsmetadb.infra.ooni.io","dc":"Amsterdam"}`
- [x] `{"v4":"37.218.242.178","name":"dataproxy.infra.ooni.io","dc":"Amsterdam"}`
- [x] `{"v4":"37.218.242.28","name":"test-ooniprobe-trusty","dc":"Amsterdam"}`
- [x] `{"v4":"37.218.242.32","name":"ooniprobe-test-xenial","dc":"Amsterdam"}`

afwrk{01..04} is my experiment with distributed parallel backfill (to use more CPUs).
amsmedadb, dataproxy are resources allocated for parts of new pipeline.
What's the destiny of other VMs?

**Comment by hellais** [comment]
> wiki.ooni.io

Is a wiki I had setup for sketching out the contextual database project. Maybe it's not the optimal wiki solution, but @agrabeli should probably comment on that.

> design.ooni.io

Is actually not booting due to eclipsis not having resources when I started it. I guess it should be killed and restarted. I plan to move the oo/design publication from github to there.

> test-qemu.infra.ooni.io
> ooniprobe-deb-testing
> test-ooniprobe-trusty
> ooniprobe-test-xenial

no idea what these are, but since some are in AMS we should consider cannibalising them for some other useful purposes.

**Comment by bassosimone** [comment]
>>    test-qemu.infra.ooni.io
>>    ooniprobe-deb-testing
>>    test-ooniprobe-trusty
>>    ooniprobe-test-xenial
>
> no idea what these are, but since some are in AMS we should consider cannibalising them for some other useful purposes.

Yeah, I also have no idea. 👍 for cannibalizing (I am looking for a build machine that I can access with `mosh` with four cores and enough RAM to build on RAM, could any of these be fit?)

**Comment by hellais** [comment]
If you don’t need a good network just spin up a machine in HKG

**Comment by darkk** [comment]
Following three are private Weasilis'es machines hosting some private data, they're being moved to his private GH account.
- 199.119.112.12, test-qemu.infra.ooni.io
- 37.218.242.28, test-ooniprobe-trusty
- 37.218.242.32, test-ooniprobe-xenial

**Comment by darkk** [comment]
> I plan to move the oo/design publication from github to there

@hellais I'd prefer it to stay on gh-pages if that's enough. What's the reason to allocate VM for static assets?

**Comment by darkk** [comment]
Killed design.ooni.io and afwrk{01..04}, shut ooniprobe-deb-testing down (to remove the image in ~ a month).

**Comment by darkk** [comment]
> to remove the image in ~ a month

Removed.

**Comment by hellais** [comment]
I will probably re-create another box for design.ooni.io though. The reason to host it on something != than github is that on github nested paths do not work (as they require some server-side stuff to map the first request to a subpath). Example: try visiting http://openobservatory.github.io/design/colors vs http://openobservatory.github.io/design and clicking on `colors`.

**Comment by darkk** [comment]
> another box

Do you mind co-hosting it with, for example, `get.ooni.io`?

> server-side stuff to map the first request to a subpath

IMHO it's not about server-side, but about webroot-anchored URLs, so it's just a matter of hosting these static webpages at their own domain. Even S3 bucket would likely work :-)
