### ISSUE TITLE
Collector has runtime exception on missing policy.yml file

### ISSUE THREAD

**Issue by joelanders** [TheTorProject/ooni-sysadmin#18]
This can be a bit confusing for administrators, as it looks like things are working until some HTTP request gives a 500 error.

I'd recommend we load the policy.yml at startup and complain / bail / write out defaults at that time.

**Comment by anadahz** [comment]
@joelanders does this still applies to the current version?

**Comment by hellais** [comment]
This is not filed under the correct component. https://github.com/TheTorProject/ooni-backend/issues/94 super-seeds this.
