### ISSUE TITLE
Meltdown fallout: measurements down for ~30m, explorer down for ~1h

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooni-sysadmin#196]
Impact: UI downtime

Timeline UTC, 11 Jan:
14:19 FIRING BlackboxDown https://measurements.ooni.torproject.org/api/v1/files
14:46 @darkk noticed the alert, restarts set of docker containers
14:49 RESOLVED BlackboxDown https://measurements.ooni.torproject.org/api/v1/files
16:34 FIRING InstanceDown ssdams.infra.ooni.io
16:35 @hellais I guess this is eclipsis rebooting machines
16:36 FIRING BlackboxDown https://explorer.ooni.torproject.org/api/reports/countByCountry
16:56 @darkk I'd start worrying at ~17:30 (data transfer time for 1.5Tb volume)
17:12 @darkk Fun fact: ssdams.infra.ooni.io booted according to control panel, but the VM is not reachable via network.
17:13 @hellais reaches out Mart@GH and Mart fixes VM firewall
17:27 RESOLVED BlackboxDown https://explorer.ooni.torproject.org/api/reports/countByCountry
17:39 RESOLVED InstanceDown ssdams.infra.ooni.io

What went wrong:
- VMs / services were unable to boot properly after reboot
- measurements ~ because of docker container restart policy, they were not auto-started after reboot
- ssdams ~ because of absent (?!) `/lib/modules` to mount tmpfs with kernel modules to use iptables to `ifup` network

What could be done to prevent relapse and decrease impact:
- [x] desktop notifications for #ooni-bots for @darkk
- [x] set `root` password to be able to log in from GH VM console
- [x] limit password login to console, e.g. limit `su` in a way that does not allow to become root from knowing the password

@hellais @bassosimone @anadahz What's your opinion, should root password be shared as-is between [`adm_logins` users](https://github.com/TheTorProject/ooni-sysadmin/blob/553ed29138d093f30f0698bbe9e98c600d706319/ansible/group_vars/all/vars.yml#L96) or should it be sliced with [`ssss`](http://point-at-infinity.org/ssss/) with 2-of-4 scheme?

**Comment by hellais** [comment]
> What's your opinion, should root password be shared as-is between adm_logins users or should it be sliced with ssss with 2-of-4 scheme?

I would suggest we just set it to something and share it between adm_logins. It's probably wise to not commit it into the ansible vault and just have each of us keep in their keychain or whatever.

**Comment by darkk** [comment]
I followed same scheme as with vault-password file: PSK is shared once, hash is stored in the vault.

See 483984057f092a1302113c087f6565024a933c70
