### ISSUE TITLE
error while evaluating conditional: set_ooniprobe_pip == true

### ISSUE THREAD

**Issue by elationfoundation** [TheTorProject/ooni-sysadmin#21]
When running the [install ooniprobe](https://github.com/TheTorProject/ooni-sysadmin#ooniprobe) ansible playlist an error occurs when evaluating the set_ooniprobe_pip conditional in the [main ooniprobe task](https://github.com/TheTorProject/ooni-sysadmin/blob/ff39aa373e6e22389dbd36e2e1b19de4ef6deff2/ansible/roles/ooniprobe/tasks/main.yml#L5).

```
TASK: [ooniprobe | Add required Debian apt repository] ************************ 
fatal: [xx.xx.xx.xx] => error while evaluating conditional: set_ooniprobe_pip == true

FATAL: all hosts have already failed -- aborting
```

To fix this error the [current line](https://github.com/TheTorProject/ooni-sysadmin/blob/ff39aa373e6e22389dbd36e2e1b19de4ef6deff2/ansible/roles/ooniprobe/tasks/main.yml#L5) can be changed to see if set_ooniprobe_pip is defined before checking if it is equal to true.

```
when: set_ooniprobe_pip is defined and set_ooniprobe_pip == 'true'
```

**Comment by anadahz** [comment]
Thank you for taking the time to test it!
https://github.com/TheTorProject/ooni-sysadmin/pull/24
