### ISSUE TITLE
error while evaluating conditional: set_supervisord == 'true'

### ISSUE THREAD

**Issue by elationfoundation** [TheTorProject/ooni-sysadmin#22]
Similar to issue #21 when running the [install ooni-backend](https://github.com/TheTorProject/ooni-sysadmin#ooni-backend) ansible playlist an error occurs when evaluating the set_supervisord  conditional in the [main ooni-backend task](https://github.com/TheTorProject/ooni-sysadmin/blob/ff39aa373e6e22389dbd36e2e1b19de4ef6deff2/ansible/roles/ooni-backend/tasks/main.yml#L4-L7).

```
TASK: [ooni-backend | Template oonibackend supervisord config] **************** 
fatal: [xx.xx.xx.xx] => error while evaluating conditional: set_supervisord == 'true'

FATAL: all hosts have already failed -- aborting
```

To fix this error the [current checks](https://github.com/TheTorProject/ooni-sysadmin/blob/ff39aa373e6e22389dbd36e2e1b19de4ef6deff2/ansible/roles/ooni-backend/tasks/main.yml#L4-L7) can be changed to see if set_supervisord is defined before checking if it is equal to true.

```
- include: supervisord.yml
  when: set_supervisord is defined and set_supervisord == 'true'
- include: fetch-HS-info.yml
  when: set_supervisord is defined and set_supervisord == 'true'
```

**Comment by elationfoundation** [comment]
NOTE: This error only occurs when set_supervisord is not set in the hosts file being used.

**Comment by anadahz** [comment]
Thank you for checking this!
https://github.com/TheTorProject/ooni-sysadmin/pull/25
