### ISSUE TITLE
group_vars not found relitive to YAML file.

### ISSUE THREAD

**Issue by elationfoundation** [TheTorProject/ooni-sysadmin#23]
The installation instructions for both [ooni-backend](https://github.com/TheTorProject/ooni-sysadmin#execute-role) and [ooniprobe](https://github.com/TheTorProject/ooni-sysadmin#execute-role-1) imply (through the path to install-ooniprobe.yml/install-oonibackend.yml) that they should be run from the root of the ooni-sysadmin repo. If done from the root of the repo the following error will occur.

```
TASK: [common | setup tor apt repo] ******************************************* 
fatal: [xx.xx.xx.xx] => One or more undefined variables: 'tor_distribution_release' is undefined

FATAL: all hosts have already failed -- aborting
```

This error occurs because ansible looks for the the group_vars folder relative to its YAML file. The error can be fixed by moving the group_vars folder into the ansible folder, or by placing a sym-link to it in the ansible folder.

**Comment by anadahz** [comment]
Thanks for reporting this!
This has been fixed at #32.
There is no need for wide default group_vars.
