### ISSUE TITLE
Implement a way for ooni-backend to reload the updated TLS certificates

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-sysadmin#57]
This is actually a ticket to overcome the limitation of Github milestones that can include only issues from same repository.
Ref: https://github.com/TheTorProject/ooni-backend/issues/90

**Comment by anadahz** [comment]
This has been implemented here: https://github.com/TheTorProject/ooni-backend/pull/91

**Comment by joelanders** [comment]
Implemented in #91?

**Comment by anadahz** [comment]
@joelanders my bad i was confused.

**Comment by anadahz** [comment]
A workaround is to add pre/post hooks to letsencrypt certificate generation that trigger a docker restart when a new certificate has been generated, [relevant code](https://github.com/TheTorProject/ooni-sysadmin/blob/2bcac4542d90cdbbde2f2e87f515b512236bed89/ansible/roles/letsencrypt/vars/main.yml#L6-14).

**Comment by anadahz** [comment]
As mentioned in https://github.com/TheTorProject/ooni-sysadmin/issues/57#issuecomment-229491960 this is not a blocker for the ooni-backend deployment.

**Comment by hellais** [comment]
Is this actually a ooni-sysadmin ticket? It seems like it would actually be more useful as a ooni-backend ticket.

**Comment by anadahz** [comment]
@hellais indeed it's an ooni-backend [issue](https://github.com/TheTorProject/ooni-backend/issues/90). 

A workaround has been added in the ansible role by using pre/post hooks as described in: https://github.com/TheTorProject/ooni-sysadmin/issues/57#issuecomment-229491960
