### ISSUE TITLE
Deploy staging/testing bouncer, collector and web_connectivity test helper

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-sysadmin#58]
For testing and implementing [this measurement-kit feature](https://github.com/measurement-kit/measurement-kit/issues/651) it would be good to have a staging/testing bouncer, collector and web_connectivity test helper that has HTTPS support.

This would make development and end-to-end testing much simpler.

**Comment by hellais** [comment]
This should be done before #61 and then once this has been tested end-to-end with ooniprobe, then we can deploy the production one in #61.

**Comment by anadahz** [comment]
This is accomplished: Deployment of  staging and testing bouncers, collectors and web_connectivity test helpers with alternate HTTPS collectors, bouncers and test helpers.
