### ISSUE TITLE
Add some A records to a domain for the stage/testing backend

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-sysadmin#60]
This task is about adding a number of A records that will resolve to the stage/testing backend server.

**Comment by hellais** [comment]
I need some IPs and a hostname to do this.

**Comment by anadahz** [comment]
[1.209.122.30]
stage.bouncer.ooni.io
stage.a.collector.ooni.io
stage.a.web-connectivity.th.ooni.io

[1.209.122.32]
test.bouncer.ooni.io
test.a.collector.ooni.io
test.a.web-connectivity.th.ooni.io

**Comment by hellais** [comment]
Sounds good. I am just going to flip the test part to be closer to the root of the domain since it's the main qualifier and I think it is semantically more correct to be placed closer to the domain it's referring to.

Hence this will be what I will create:

# Staging
```
stage.ooni.io A 1.209.122.30
bouncer.stage.ooni.io A 1.209.122.30
a.collector.stage.ooni.io A 1.209.122.30
a.web-connectivity.th.stage.ooni.io A 1.209.122.30
```

# Testing
```
test.ooni.io A 1.209.122.32
bouncer.test.ooni.io A 1.209.122.32
a.collector.test.ooni.io A 1.209.122.32
a.web-connectivity.th.test.ooni.io A 1.209.122.32
```

**Comment by hellais** [comment]
Created.

Should soon propagate.

**Comment by hellais** [comment]
Since a.collector.test.ooni.io was taken by the Measurement-Kit testing collector (as @bassosimone pointed out to me)

I created this instead:

```
b.collector.test.ooni.io A 1.209.122.32
```

**Comment by anadahz** [comment]
@hellais it seems that `bouncer.test.ooni.io` points to `199.119.112.211`

**Comment by hellais** [comment]
Oh right. I was pointing to both. Removed the record for `1.209.122.32`

**Comment by anadahz** [comment]
@hellais thank you!
