### ISSUE TITLE
Change A records for stage and test ooni-backends

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-sysadmin#73]
Stage and test ooni-backends have been migrated to a new server with a different
set of IPs. Please change/set the following DNS A records:

**Staging**
```
stage.ooni.io A 37.218.240.139
bouncer.stage.ooni.io A 37.218.240.139
b.collector.stage.ooni.io A 37.218.240.139
a.web-connectivity.th.stage.ooni.io A 37.218.240.139
```

**Testing**

```
test.ooni.io A 37.218.240.140
bouncer.test.ooni.io A 37.218.240.140
b.collector.test.ooni.io A 37.218.240.140
a.web-connectivity.th.test.ooni.io A 37.218.240.140
```

**Comment by hellais** [comment]
Created all the needed A records.

**Comment by anadahz** [comment]
@hellais could you please make sure that the A records are pointing to the correct IPs 
(re: https://github.com/measurement-kit/measurement-kit/issues/864) ?

**Comment by hellais** [comment]
It seems like:

```
a.web-connectivity.th.test.ooni.io A 37.218.240.140
b.collector.stage.ooni.io A 37.218.240.139
```

were missing.

All should now be good.

Wait a bit for the records to propagate.

**Comment by anadahz** [comment]
According to https://github.com/TheTorProject/ooni-sysadmin/issues/60#issuecomment-224708279 
 we need to replace `a.collector.test.ooni.io` with `b.collector.test.ooni.io`.
I also updated https://github.com/TheTorProject/ooni-sysadmin/issues/73#issue-181073709
If we don't want to use `a.collector.test.ooni.io` I can make the change to the current testing ooni-backend (https://github.com/TheTorProject/ooni-sysadmin/blob/master/group_vars/testing#L6).

The nicest way will be to have another testing/stage ooni-backend instances for MK.

**Comment by hellais** [comment]
What exactly do you need me to do? Is some A record still missing?
