### ISSUE TITLE
Make the canonical collector and test helpers listen on port 443

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-sysadmin#74]
It seems like it's fairly common for some networks (such as mobile ones) to block access to anything that is not traffic to common ports.

Currently the canonical collector binds on port 4441 and the canonical web connectivity test helpers binds on 4442.

It would be great if we could setup another machine just to host the collector and web connectivity test helper that has a dedicated IP for each of those services.

The added benefit of this would be that of being able to divert clients to another working collector from the bouncer (that would then reside on it's own machine) in case we encounter difficulties with it.

**Comment by anadahz** [comment]
In order for the deployment to take place we 'll be needing a bouncer base file pointing to all collectors, and test helpers instances, such as the example below:

```
collector:
  httpo://s2zznrn5jxfgkaom.onion:
    collector-alternate:
    - { address: 'https://a.collector.stage.ooni.io:4441', type: 'https'}
    - { address: 'http://a.collector.stage.ooni.io:8081', type: 'http'}
    - { address: 'https://{{ collector_domain }}:{{ tls_collector_port }}', type: 'https'}
    - { address: 'http://{{ collector_domain }}:{{ tcp_collector_port }}', type: 'http'}
    test-helper:
      {dns: '213.138.109.232:57004',
       http-return-json-headers: 'http://93.95.227.200',
       tcp-echo: '213.138.109.232',
       web-connectivity: 'ebckmavdjlxhnw27.onion',
       traceroute: '213.138.109.232'}
    test-helper-alternate:
      web-connectivity:
      - {address: 'ebckmavdjlxhnw27.onion', type: 'onion'}
      - {address: 'https://a.web-connectivity.th.stage.ooni.io:4442', type: 'https'}
      - {address: 'http://a.web-connectivity.th.stage.ooni.io:8082', type: 'http'}
      - {address: 'https://{{ web_connectivity_domain }}:{{ tls_web_connectivity_port }}', type: 'https'}
      - {address: 'http://{{ web_connectivity_domain }}:{{ tcp_web_connectivity_port }}', type: 'http'}
```

**Comment by hellais** [comment]
I see that you are specifying in here also staging collectors and test helpers. We should exclude these from the production collector and just include the ones that are production.

I would imagine the bouncer file for the production deployment would become something like this:

**current bouncer.yaml**
```json
collector:
  httpo://ihiderha53f36lsd.onion:
    collector-alternate:
    - {address: 'https://a.collector.ooni.io:4441', type: https}
    - {address: 'https://das0y2z2ribx3.cloudfront.net', front: a0.awsstatic.com, type: cloudfront}
    test-helper: {dns: '213.138.109.232:57004', http-return-json-headers: 'http://38.107.216.10:80',
      ssl: 'https://213.138.109.232', tcp-echo: 213.138.109.232, traceroute: 213.138.109.232,
      web-connectivity: 'httpo://7jne2rpg5lsaqs6b.onion'}
    test-helper-alternate:
      web-connectivity:
      - {address: 'https://a.web-connectivity.th.ooni.io:4442', type: https}
      - {address: 'https://d2vt18apel48hw.cloudfront.net', front: a0.awsstatic.com,
        type: cloudfront}
```

**new bouncer.yaml**
```json
collector:
  httpo://ihiderha53f36lsd.onion:
    collector-alternate:
    - {address: 'https://a.collector.ooni.io', type: https} # <-- Changed this line to be port 443
    - {address: 'https://das0y2z2ribx3.cloudfront.net', front: a0.awsstatic.com, type: cloudfront}
    test-helper: {dns: '213.138.109.232:57004', http-return-json-headers: 'http://38.107.216.10:80',
      ssl: 'https://213.138.109.232', tcp-echo: 213.138.109.232, traceroute: 213.138.109.232,
      web-connectivity: 'httpo://7jne2rpg5lsaqs6b.onion'}
    test-helper-alternate:
      web-connectivity:
      - {address: 'https://a.web-connectivity.th.ooni.io', type: https} # <-- Changed this line to be port 443
      - {address: 'https://d2vt18apel48hw.cloudfront.net', front: a0.awsstatic.com,
        type: cloudfront}
```

The only two changed that should happen are those related to the https collector and https web connectivity test helpers. It may actually be wiser, though, so that we don't have to worry about synchronising with DNS propagation time, to setup `b.collector.ooni.io` as a new record and update the new bouncer to use that.

Do you need anymore information to proceed?

**Comment by anadahz** [comment]
Collector `b.collector.ooni.io` and web-connectivity test helper `b.web-connectivity.th.ooni.io` on port 443 have been deployed.
Canonical's bouncer configuration should change accordingly and an announcement to the mailing list should follow.

**Comment by anadahz** [comment]
This is implemented.
