### ISSUE TITLE
Auto renewal of SSL certificated is broken on the testing collector

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-sysadmin#80]
I see that there is a cronjob in place to make SSL certs for the testing collector renew automatically, but it doesn't seem to work.

In particular running:

```
certbot  certonly --standalone --standalone-supported-challenges http-01 --noninteractive --text --agree-tos --email admin@openobservatory.org --domains test.ooni.io,bouncer.test.ooni.io,b.collector.test.ooni.io,a.web-connectivity.th.test.ooni.io --pre-hook "docker stop ooni-backend-testing-bouncer" --post-hook "cp /etc/letsencrypt/live/test.ooni.io/privkey.pem /etc/letsencrypt/live/test.ooni.io/fullchain.pem  /data/testing-bouncer/tls   && docker start ooni-backend-testing-bouncer"  --pre-hook "docker stop ooni-backend-testing-bouncer" --post-hook "cp /etc/letsencrypt/live/test.ooni.io/privkey.pem /etc/letsencrypt/live/test.ooni.io/fullchain.pem  /data/testing-bouncer/tls   && docker start ooni-backend-testing-bouncer"
```

Produces:

```
-------------------------------------------------------------------------------
The program docker-proxy (process ID 16420) is already listening on TCP port 80.
This will prevent us from binding to that port. Please stop the docker-proxy
program temporarily and then try again.
-------------------------------------------------------------------------------
At least one of the (possibly) required ports is already taken.
```

This has lead to the current testing instances (the ones used by measurement-kit) to not be available for 48 hours, due to this certificate issue.

I am going to proceed now with manually renewing them.

**Comment by anadahz** [comment]
This bug occurs because certbot complains if any network interface on host uses port 80.
This bug affects oonibackend deployments hosted on the same host (eg: testing, staging oonibackend bundle containers).

**Comment by anadahz** [comment]
Deploying the testing oonibackend bundle (that includes the collector) on a separate instance (as there is no need for multiple backend bundle on the same host) resolves this bug.
