### ISSUE TITLE
tighten sync-user permissions with rrsync

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooni-sysadmin#90]
`sync-user` can execute arbitrary command at the moment.
IMHO, it makes sense to limit it with `command="$HOME/bin/rrsync /data/fqdn/renamed",no-agent-forwarding,no-port-forwarding,no-pty,no-user-rc,no-X11-forwarding ssh-rsa...` in authorized_keys to reduce privileges.

**Comment by bassosimone** [comment]
Yeah, I think this would be a good improvement!

**Comment by anadahz** [comment]
The sync user has now only access to the rrsync script for the collector and bouncer endpoints.
Thanks for reporting this @darkk .
