### ISSUE TITLE
Consolidate all inventories so that anyone of us can deploy any piece of the infrastructure

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-sysadmin#91]
@darkk suggested that it's possible to use [ansible vaults](http://docs.ansible.com/ansible/playbooks_vault.html) to store secrets encrypted and commit them directly to this tree.

I think we agree on the fact that there are fairly few secrets inside of the actual inventories (I believe we don't consider hostnames, IPs and ports to be secret).

I would be good to start doing this for at least one of the services so that we have an idea of how it works for one service and @darkk and I can start learning how to deploy them.

This would also I believe encourage me to use ooni-sysadmin more and do less deployment tasks manually.

**Comment by SuperQ** [comment]
:+1:, Ansible vaults are good for secrets.  We use them for FOSDEM deployment.

**Comment by darkk** [comment]
Seems, the process is converging -- new hosts are deployed using public inventory, old one are cleaned up (e.g. #123).
