### ISSUE TITLE
Improve accounts on infrastructure

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-sysadmin#92]
@anadahz has been talking about improving how accounts are managed and created on the various VMs that run pieces of ooni infrastructure.

I don't have a clear understanding of what the plans are for that, the thing I do remember from these discussions is that having us all login as root on the machines is bad and we should have per user accounts.

@anadahz what are your ideas on this topic?

**Comment by darkk** [comment]
My current idea is to have separate ansible role that can be applied to every VM with root access as a part of _common_ VM template. Some highlights:
- use same UID on all servers, choose uid >= 10000 to avoid clashes with manually-created users as usual UID_MIN is 500 or 1000
- disable password-based logins in /etc/shadow
- add `sudo` with NOPASSWD

Also, we don't consider 2FA at the moment.

**Comment by darkk** [comment]
I think, this ticket may be closed, `dom0-bootstrap.yml` playbook manages that.
I'm still unsure if static UIDs is a good idea or waste of time, but right now we stick to static UIDs.
